lue, 245, 245, cv.THRESH_BINARY)
        # _, green = cv.threshold(green, 245, 245, cv.THRESH_BINARY)
        # xor_frame = cv.bitwise_xor(red, blue)
        # xor_frame = cv.bitwise_xor(xor_frame, green)
        # cv.imshow('xor', xor_frame)